# Generated by Django 3.2.7 on 2021-09-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='nofity_pref',
            new_name='notify_pref',
        ),
    ]
