# Generated by Django 3.2.7 on 2021-09-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_rename_nofity_pref_userpreference_notify_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
